dataset:
  name: ContrastivePointclouds
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  steps_per_epoch_train: 1000

model:
  name: ContrastivePointPillars
  ckpt_path: # path/to/your/checkpoint

  batcher: "ignore"

  point_cloud_range: [0, -2, -1, 5, 2, 1]
  classes: ['Car']

  loss:
    focal:
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1:
      beta: 0.11
      loss_weight: 2.0
    cross_entropy:
      loss_weight: 0.2

  voxelize:
    max_num_points: 32
    voxel_size: &vsize
      [0.05, 0.05, 2]
    max_voxels: [16000, 40000]
  
  voxel_encoder:
    in_channels: 3
    feat_channels: [64]
    voxel_size: *vsize

  scatter:
    in_channels: 64
    output_shape: [112, 80]

  backbone:
    in_channels: 64
    out_channels: [64, 128, 256]
    layer_nums: [3, 5, 5]
    layer_strides: [2, 2, 2]

  neck:
    in_channels: [64, 128, 256]
    out_channels: [128, 128, 128]
    upsample_strides: [1, 2, 4]
    use_conv_for_no_stride: false
  
  slots:
    in_channels: 384
    out_channels: 4
  
  augment:
    PointShuffle: True
    ObjectRangeFilter: True
    ObjectSample:
      min_points_dict:
        Car: 5
        Pedestrian: 10
        Cyclist: 10
      sample_dict:
        Car: 15
        Pedestrian: 10
        Cyclist: 10


pipeline:
  name: ContrastiveLearning
  test_compute_metric: true
  batch_size: 1
  val_batch_size: 1
  test_batch_size: 1
  save_ckpt_freq: 1
  validation_freq: 1
  max_epoch: 200
  main_log_dir: ./logs
  train_sum_dir: train_log
  grad_clip_norm: 2
  slots_save_dir: ./slot_saves/

  optimizer:
    lr: 0.001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [0.7]
  similar_classes: {
    Van: Car,
    Person_sitting: Pedestrian
  }
  difficulties: [0, 1, 2]
    
